name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Run code formatting checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build docker image
      run: make docker/build
    - name: unit tests
      run: make docker/tests