name: Scheduled FitBot run - Test1

on:
  schedule:
  - cron: "15 30 * * 0-4,6"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: make docker/build
      - name: Sleep until specific time
        run: |
          target_hour=14
          target_minute=50
          target_second=0
          current_hour=$(date +%H)
          current_minute=$(date +%M)
          current_second=$(date +%S)

          # Remove leading zeros
          current_hour=$((10#$current_hour))
          current_minute=$((10#$current_minute))
          current_second=$((10#$current_second))
          
          target_time_in_seconds=$((target_hour * 3600 + target_minute * 60 + target_second))
          current_time_in_seconds=$((current_hour * 3600 + current_minute * 60 + current_second))

          echo "current_hour: $current_hour $current_minute $current_second"
          echo "target_time_in_seconds: $target_time_in_seconds"
          echo "current_time_in_seconds: $current_time_in_seconds"
          
          if [ $current_time_in_seconds -ge $target_time_in_seconds ]; then
            sleep_duration=0
          else
            sleep_duration=$((target_time_in_seconds - current_time_in_seconds))
          fi

          echo "Sleeping for $sleep_duration seconds until the target time"
          sleep $sleep_duration
          
      - name: Run secondary_fitbot
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals='{\"0\":{\"time\":\"1330\",\"name\":\"Endurance\"}}' -e box-name=laucalahealthcrossfit -e box-id=9907 -e days-in-advance=2 fitbot
